# Project-wide Gradle settings.
# https://docs.gradle.org/current/userguide/build_environment.html

# JVM arguments for the Gradle daemon.
org.gradle.jvmargs=-Xmx4096m -XX:+UseParallelGC -Dfile.encoding=UTF-8

# Build performance
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

kotlin.code.style=official

# Use AndroidX packages.
android.useAndroidX=true
# Each library's R class contains only its own resources.
android.nonTransitiveRClass=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
