package com.hisabkitab.core.icons

/** A selectable category icon: a stable [key] (persisted in the database) and its drawable. */
data class CategoryIcon(val key: String, val resId: Int)

/**
 * Typed lookup for the bundled category icons.
 *
 * Keys (`icon_1` … `icon_N`) are what the database stores, so they must never be renamed.
 * Resolving through this table instead of `Resources.getIdentifier` keeps the icons safe
 * from resource shrinking and avoids reflection.
 */
object CategoryIcons {

    const val DEFAULT_KEY = "icon_97"

    val all: List<CategoryIcon> = listOf(
        CategoryIcon("icon_1", R.drawable.icon_1),
        CategoryIcon("icon_2", R.drawable.icon_2),
        CategoryIcon("icon_3", R.drawable.icon_3),
        CategoryIcon("icon_4", R.drawable.icon_4),
        CategoryIcon("icon_5", R.drawable.icon_5),
        CategoryIcon("icon_6", R.drawable.icon_6),
        CategoryIcon("icon_7", R.drawable.icon_7),
        CategoryIcon("icon_8", R.drawable.icon_8),
        CategoryIcon("icon_9", R.drawable.icon_9),
        CategoryIcon("icon_10", R.drawable.icon_10),
        CategoryIcon("icon_11", R.drawable.icon_11),
        CategoryIcon("icon_12", R.drawable.icon_12),
        CategoryIcon("icon_13", R.drawable.icon_13),
        CategoryIcon("icon_14", R.drawable.icon_14),
        CategoryIcon("icon_15", R.drawable.icon_15),
        CategoryIcon("icon_16", R.drawable.icon_16),
        CategoryIcon("icon_17", R.drawable.icon_17),
        CategoryIcon("icon_18", R.drawable.icon_18),
        CategoryIcon("icon_19", R.drawable.icon_19),
        CategoryIcon("icon_20", R.drawable.icon_20),
        CategoryIcon("icon_21", R.drawable.icon_21),
        CategoryIcon("icon_22", R.drawable.icon_22),
        CategoryIcon("icon_23", R.drawable.icon_23),
        CategoryIcon("icon_24", R.drawable.icon_24),
        CategoryIcon("icon_25", R.drawable.icon_25),
        CategoryIcon("icon_26", R.drawable.icon_26),
        CategoryIcon("icon_27", R.drawable.icon_27),
        CategoryIcon("icon_28", R.drawable.icon_28),
        CategoryIcon("icon_29", R.drawable.icon_29),
        CategoryIcon("icon_30", R.drawable.icon_30),
        CategoryIcon("icon_31", R.drawable.icon_31),
        CategoryIcon("icon_32", R.drawable.icon_32),
        CategoryIcon("icon_33", R.drawable.icon_33),
        CategoryIcon("icon_34", R.drawable.icon_34),
        CategoryIcon("icon_35", R.drawable.icon_35),
        CategoryIcon("icon_36", R.drawable.icon_36),
        CategoryIcon("icon_37", R.drawable.icon_37),
        CategoryIcon("icon_38", R.drawable.icon_38),
        CategoryIcon("icon_39", R.drawable.icon_39),
        CategoryIcon("icon_40", R.drawable.icon_40),
        CategoryIcon("icon_41", R.drawable.icon_41),
        CategoryIcon("icon_42", R.drawable.icon_42),
        CategoryIcon("icon_43", R.drawable.icon_43),
        CategoryIcon("icon_44", R.drawable.icon_44),
        CategoryIcon("icon_45", R.drawable.icon_45),
        CategoryIcon("icon_46", R.drawable.icon_46),
        CategoryIcon("icon_47", R.drawable.icon_47),
        CategoryIcon("icon_48", R.drawable.icon_48),
        CategoryIcon("icon_49", R.drawable.icon_49),
        CategoryIcon("icon_50", R.drawable.icon_50),
        CategoryIcon("icon_51", R.drawable.icon_51),
        CategoryIcon("icon_52", R.drawable.icon_52),
        CategoryIcon("icon_53", R.drawable.icon_53),
        CategoryIcon("icon_54", R.drawable.icon_54),
        CategoryIcon("icon_55", R.drawable.icon_55),
        CategoryIcon("icon_56", R.drawable.icon_56),
        CategoryIcon("icon_57", R.drawable.icon_57),
        CategoryIcon("icon_58", R.drawable.icon_58),
        CategoryIcon("icon_59", R.drawable.icon_59),
        CategoryIcon("icon_60", R.drawable.icon_60),
        CategoryIcon("icon_61", R.drawable.icon_61),
        CategoryIcon("icon_62", R.drawable.icon_62),
        CategoryIcon("icon_63", R.drawable.icon_63),
        CategoryIcon("icon_64", R.drawable.icon_64),
        CategoryIcon("icon_65", R.drawable.icon_65),
        CategoryIcon("icon_66", R.drawable.icon_66),
        CategoryIcon("icon_67", R.drawable.icon_67),
        CategoryIcon("icon_68", R.drawable.icon_68),
        CategoryIcon("icon_69", R.drawable.icon_69),
        CategoryIcon("icon_70", R.drawable.icon_70),
        CategoryIcon("icon_71", R.drawable.icon_71),
        CategoryIcon("icon_72", R.drawable.icon_72),
        CategoryIcon("icon_73", R.drawable.icon_73),
        CategoryIcon("icon_74", R.drawable.icon_74),
        CategoryIcon("icon_75", R.drawable.icon_75),
        CategoryIcon("icon_76", R.drawable.icon_76),
        CategoryIcon("icon_77", R.drawable.icon_77),
        CategoryIcon("icon_78", R.drawable.icon_78),
        CategoryIcon("icon_79", R.drawable.icon_79),
        CategoryIcon("icon_80", R.drawable.icon_80),
        CategoryIcon("icon_81", R.drawable.icon_81),
        CategoryIcon("icon_82", R.drawable.icon_82),
        CategoryIcon("icon_83", R.drawable.icon_83),
        CategoryIcon("icon_84", R.drawable.icon_84),
        CategoryIcon("icon_85", R.drawable.icon_85),
        CategoryIcon("icon_86", R.drawable.icon_86),
        CategoryIcon("icon_87", R.drawable.icon_87),
        CategoryIcon("icon_88", R.drawable.icon_88),
        CategoryIcon("icon_89", R.drawable.icon_89),
        CategoryIcon("icon_90", R.drawable.icon_90),
        CategoryIcon("icon_91", R.drawable.icon_91),
        CategoryIcon("icon_92", R.drawable.icon_92),
        CategoryIcon("icon_93", R.drawable.icon_93),
        CategoryIcon("icon_94", R.drawable.icon_94),
        CategoryIcon("icon_95", R.drawable.icon_95),
        CategoryIcon("icon_96", R.drawable.icon_96),
        CategoryIcon("icon_97", R.drawable.icon_97),
        CategoryIcon("icon_98", R.drawable.icon_98),
        CategoryIcon("icon_99", R.drawable.icon_99),
        CategoryIcon("icon_100", R.drawable.icon_100),
        CategoryIcon("icon_101", R.drawable.icon_101),
        CategoryIcon("icon_102", R.drawable.icon_102),
        CategoryIcon("icon_103", R.drawable.icon_103),
        CategoryIcon("icon_104", R.drawable.icon_104),
        CategoryIcon("icon_105", R.drawable.icon_105),
        CategoryIcon("icon_106", R.drawable.icon_106),
        CategoryIcon("icon_107", R.drawable.icon_107),
        CategoryIcon("icon_108", R.drawable.icon_108),
        CategoryIcon("icon_109", R.drawable.icon_109),
        CategoryIcon("icon_110", R.drawable.icon_110),
        CategoryIcon("icon_111", R.drawable.icon_111),
        CategoryIcon("icon_112", R.drawable.icon_112),
        CategoryIcon("icon_113", R.drawable.icon_113),
        CategoryIcon("icon_114", R.drawable.icon_114),
        CategoryIcon("icon_115", R.drawable.icon_115),
        CategoryIcon("icon_116", R.drawable.icon_116),
        CategoryIcon("icon_117", R.drawable.icon_117),
        CategoryIcon("icon_118", R.drawable.icon_118),
        CategoryIcon("icon_119", R.drawable.icon_119),
        CategoryIcon("icon_120", R.drawable.icon_120),
        CategoryIcon("icon_121", R.drawable.icon_121),
        CategoryIcon("icon_122", R.drawable.icon_122),
        CategoryIcon("icon_123", R.drawable.icon_123),
        CategoryIcon("icon_124", R.drawable.icon_124),
        CategoryIcon("icon_125", R.drawable.icon_125),
        CategoryIcon("icon_126", R.drawable.icon_126),
        CategoryIcon("icon_127", R.drawable.icon_127),
        CategoryIcon("icon_128", R.drawable.icon_128),
        CategoryIcon("icon_129", R.drawable.icon_129),
        CategoryIcon("icon_130", R.drawable.icon_130),
        CategoryIcon("icon_131", R.drawable.icon_131),
        CategoryIcon("icon_132", R.drawable.icon_132),
        CategoryIcon("icon_133", R.drawable.icon_133),
        CategoryIcon("icon_134", R.drawable.icon_134),
        CategoryIcon("icon_135", R.drawable.icon_135),
        CategoryIcon("icon_136", R.drawable.icon_136),
        CategoryIcon("icon_137", R.drawable.icon_137),
        CategoryIcon("icon_138", R.drawable.icon_138),
        CategoryIcon("icon_139", R.drawable.icon_139),
    )

    private val byKey: Map<String, CategoryIcon> = all.associateBy { it.key }

    /** Returns the drawable for [key], falling back to a generic icon for unknown keys. */
    fun resolve(key: String): Int = (byKey[key] ?: byKey.getValue(DEFAULT_KEY)).resId

    fun contains(key: String): Boolean = key in byKey
}
